### ISSUE TITLE
Unable to install srsGUI in ubuntu 14.04

### ISSUE THREAD

**Issue by sagniknitr** [srsLTE/srsGUI#3]
All the steps are followed as shown in the tutorial.However as soon as I start the 'make' command, it stops with the error as shown in the picture.
![screenshot from 2017-05-24 16 30 48](https://cloud.githubusercontent.com/assets/17951883/26400486/b0c4da38-409e-11e7-87fc-18c6fa11e359.png)

**Comment by andrepuschmann** [comment]
Hey, 
this should work in theory. It's clearly an issue with qt. Have you executed the apt-get command as mentioned in the readme? If yes, it may still be that a qt-dev package is missing on your system, hence, srsGUI isn't building and not linking.

**Comment by andrepuschmann** [comment]
Closing this due to missing feedback from original author
