### ISSUE TITLE
Build with Qt5

### ISSUE THREAD

**Issue by mnhauke** [srsLTE/srsGUI#5]
Most linux distributions (debian/ubuntu/fedora/suse/gentoo) dropped support for Qt4 last year and thus also srsGUI is not build anymore.

Are there any plans to support Qt5 ?

https://wiki.debian.org/Qt4Removal
https://lists.opensuse.org/opensuse-kde/2019-03/msg00000.html

**Comment by andrepuschmann** [comment]
I am running Ubuntu 19.10 and I can build srsGUI ok. As soon as we have issues with it we probably port srsGUI to Qt5 but of course, if someone does it earlier and submits a PR, we are happy to review it.

**Comment by andrepuschmann** [comment]
Qt5 support added in upcoming release.
