### ISSUE TITLE
GUI ERROR:   X Error: BadAccess (attempt to access private resource denied) 10

### ISSUE THREAD

**Issue by jin-github1002** [srsLTE/srsGUI#9]
hello,everyone,
I run LimeSDR with srsLTE. When i set  gui to be true in enb.conf or ue.conf, there are lots of errors with the GUI feature. Does anyone know whats wrong? How to solve it?
Any help will be appreciated. Thanks so much.

(base) dell@dell-XPS-15-9550:~/srsLTE/srsenb$ sudo srsenb enb.conf

Built in Release mode using commit c2de0c67 on branch master.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file enb.conf...
Opening 1 RF devices with 1 RF channels...
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

Soapy has found device #0: addr=1d50:6108, driver=lime, label=LimeSDR-USB [USB 3.0] 9081C05C13524, media=USB 3.0, module=FX3, name=LimeSDR-USB, serial=0009081C05C13524, 
[INFO] Make connection: 'LimeSDR-USB [USB 3.0] 9081C05C13524'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeSDR-USB
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
Setting up Rx stream with 1 channel(s)
Setting up Tx stream with 1 channel(s)
[INFO] RX LPF configured
[INFO] RX LPF configured
Set Rx bandwidth to 2.50 MHz
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 5.00 MHz
Available device sensors: 
 - clock_locked
 - lms7_temp
Available sensors for Rx channel 0: 
 - lo_locked
[INFO] Tx calibration finished
[INFO] Rx calibration finished
State of gain elements for Rx channel 0 (AGC not supported):
 - TIA: 9.00 dB
 - LNA: 30.00 dB
 - PGA: -4.00 dB
State of gain elements for Tx channel 0 (AGC not supported):
 - PAD: 45.00 dB
 - IAMP: 0.00 dB
Rx antenna set to LNAL
Tx antenna set to BAND1

Warning burst preamble is not calibrated for device lime. Set a value manually

Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
Setting Sampling frequency 11.52 MHz
Failed to connect to MME - retrying in 10 seconds

==== eNodeB started ===
Type <t> to view trace
Starting plot for worker_id=0
[INFO] RX LPF configured
Set Rx bandwidth to 8.64 MHz
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x4c00012
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x4c0001f
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 8.64 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 8.64 MHz
[INFO] Tx calibration finished
[INFO] Rx calibration finished
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x4c00020

**Comment by andrepuschmann** [comment]
Is this over SSH with X11 forwarding?

**Comment by jin-github1002** [comment]
@andrepuschmann  No. I did not use a remote computer to login the ue computer. And i have the save error in the enb+epc computer too. I can see a window without anything in it. I guess the window is opened by srsGUI. But nothing in it even though a frame. Could you help give some recommendations?

**Comment by jin-github1002** [comment]
typo. The save error --> the same error

**Comment by jin-github1002** [comment]
@andrepuschmann  And after disabled GUI feature i can not attach the srsUE to eNB. i tried such .conf as follows. Could you please give some recommendations?
UE is on a computer. eNB+epc is on a computer. Both RF end are LimeSDR USB. I do not use a USIM card. I think im using the ue number in the ue.conf. The two LimeSDR is near with about 20-30cm distance.
 
1\ the default .conf documents.  ue can attach the network before. But now it can not.
2\ change the prb =15 in enb.conf. I tried many times.  UE attached the network only once.
3\ change the prb to 20 or 10 in enb.conf. I saw prb=15 from the ue terminal.
4\ change prb=100 in enb.conf, attach failed.
5\ change prb = 6(saw it in the srsLTE document). error about SIB.conf

I really dont know how to connet ue to enb. and the connection can be maintained for a longer time. before today i have the connection to last for no longer than 2 minutes. attached. then disconnected.

**Comment by andrepuschmann** [comment]
You are mixing issues here. One is the GUI problem and the other the connection establishment. Check your antenna configuration, it seems you are using the LNAL and BAND1 antenna ports which only work for sub GHz frequencies. But there are many threads on the ML and resolved issues on GH so please consult those first.

**Comment by andrepuschmann** [comment]
According to [this](https://github.com/P0cL4bs/WiFi-Pumpkin-deprecated/issues/53) your issue can be fixed with `export QT_X11_NO_MITSHM=1`. So doesn't seem to be srsGUI related.

**Comment by jin-github1002** [comment]
@andrepuschmann Thanks a lot. I will try it right now. 
I am confused if it is related the version of qt.i have qt4 and qt5 on my computer. Which one  is used in srsgui? How does srsgui find a version of qt to use?

**Comment by faluco** [comment]
@jin-github1002 Depends on the release you're using: 1.0 will use qt4, while 2.0 will only use qt5. Yoy can find further info in the release tab.

**Comment by jin-github1002** [comment]
@andrepuschmann 
i run: 
export QT_X11_NO_MITSHM=1
then sudo srsenb enb.conf
the GUI is still erorr. 
I attached it here.
Could you please give any help？
![Screenshot from 2020-05-16 00-36-40](https://user-images.githubusercontent.com/56423419/82110569-65697300-970d-11ea-83dc-b51521271ce7.png)
